apiVersion: apiextensions.k8s.io/v1
kind: CronCrawlerJob
metadata:
  # name 必须匹配下面的spec字段：<plural>.<group>
  name: cron-crawler-jobs
  namespace: datacrawl
spec:
  schedule: "*/5 * * * *"
  image:
  project: "newspapers"
  category: "test"
  parallelism: 5
  runner_args: ""
