apiVersion: batch/v1beta1
kind: Job
metadata:
  namespace: datacrawl
  name: crawler-publisher
  labels:
    app: crawler-publisher
spec:
  template:
    spec:
      volumes:
        - name: run_list
          hostPath:
            path: ../run_list
      Containers:
        - name: crawler-puller
          image: crawler-puller:0.0.1
          env:
            - name: PROJECT
              value: "newspapers"
            - name: CATEGORY
              value: "test"
          command:
            - bash
            - "-c"
            - |
              set -ex
              run_list_path=/run_list/$PROJECT/$CATEGORY
              host=redis-app-0.redis-service.datacrawl.svc.cluster.local
              redis_key=$PROJECT"_"$CATEGORY
              cat $run_list_path | sed -r "s/(.*)/sadd redis-key \1/"| redis-cli -h $host -c $host:6379 --pipe
          volumeMounts:
            - name: run_list
              mountPath: /run_list
